### ISSUE TITLE
Duplicate jQuery causing the issues

### ISSUE THREAD

**Issue by VivekShingala** [queueit/KnownUser.V3.MagentoV2#5]
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

This line in admin.phtml file, causing javascript errors on Admin -> Store -> QueueIt KnownUser -> Admin page.

Below JS errors we are getting in the console tab.

1. (index):120 Uncaught TypeError: Cannot read property 'RFC_2822' of undefined
1. notification.js:13 Uncaught TypeError: $.widget is not a function

Please remove inclusion of jquery from the page.
view/adminhtml/templates/admin.phtml

**Comment by VivekShingala** [comment]
The javascript code in this file has other issues. 

It is not binging to require js which breaks when we use bundling in Magento and the code has `debugger;` statements as well.

**Comment by sarooghi** [comment]
It is fixed in the new version
