### ISSUE TITLE
User manual is not correct

### ISSUE THREAD

**Issue by leo-leung** [queueit/KnownUser.V3.MagentoV2#6]
The user manual "mkdir -p QueueIT/knownuser" is not correct, the name convention is not consistent with the di.xml and Class autoload in Magento.
As a result, you will see many "class not found" error.

To unify, suggest to replace :
1) "mkdir -p QueueIT/knownuser"  to "mkdir -p QueueIT/KnownUser" 

2) Replace any matching class in di.xml  to QueueIT\KnownUser  (case sensitive)

3) Replace any Queueit_KnownUser  to QueueIT_KnownUser (case sensitive)

**Comment by sp0x** [comment]
The readme has been updated with the correct casing
