### ISSUE TITLE
Deprecations fixes for Magento 2.4.5

### ISSUE THREAD

**Issue by gianstraf** [queueit/KnownUser.V3.MagentoV2#7]
Hi Support,
the following errors are discovered using the Upgrade Compatibility Tool (UCT) provided with Magento 2.4.5:

https://github.com/queueit/KnownUser.V3.MagentoV2/blob/236a98d4dd89bb86981ed0ccdf3ec87a0dc514f9/Observer/KnownUserObserver.php#L87
`[5007] Line 87: The use of function is_null() is discouraged; use strict comparison "=== null"() instead`

https://github.com/queueit/KnownUser.V3.MagentoV2/blob/236a98d4dd89bb86981ed0ccdf3ec87a0dc514f9/view/adminhtml/templates/admin.phtml#L416
`[5082] Line 416: The use of $this in templates is deprecated. Use $block instead.`

https://github.com/queueit/KnownUser.V3.MagentoV2/blob/236a98d4dd89bb86981ed0ccdf3ec87a0dc514f9/Controller/Adminhtml/Admin/UploadConfig.php#L60
Possible php error on Magento 2.4.5 and PHP 8.1, if `$strConfig` is not a string

Thank you

**Comment by 3520kramer** [comment]
We are closing this due to it not being relevant currently. We will revisit this during next round of updates for this connector
